### ISSUE TITLE
Add a knob to start/stop DVR without restart

### ISSUE THREAD

**Issue by seriyps** [OpenIPC/PixelPilot_rk#14]
Current implementation of ground station just kills `pixelpilot` with signal 15 which does not shut down pixelpilot gracefully (so mp4 dvr file is not closed properly etc). It also causes the video breakup when it restarts.

I believe there should be some knob added to start-stop DVR on-the-fly.

* One option is let's say SIGUSR handler? So groundstation could use `kill SIGUSR1 -p <pp-pid>` to start/stop DVR.
* Another option is to provide UNIX socket that can take reconfiguration commands.
* Third option is to build an HTTP API, but it is much more complex task IMO, but provides much more opportunities.

It would most likely require a slight change in the command line format though.

**Comment by luastoned** [comment]
I think as a first step signals are the cheapest way to go forward, as we only have record for now.
Long term I'd like more options, probably a HTTP API, some tiny libs to consider:

- https://github.com/kissbeni/tinyhttp
- https://github.com/yhirose/cpp-httplib

**Comment by seriyps** [comment]
> as we only have record for now

I can easily imagine some users might wan to have an option to enable/disale OSD as well. But I agree in principle - we do it the easy way first and build more flexible solution if we see there is a demand and we have resources
