### ISSUE TITLE
Make wfb-ng mavlink injected system_id and component_id configurable

### ISSUE THREAD

**Issue by seriyps** [OpenIPC/PixelPilot_rk#21]
It seems that wfb-ng injects artificial Mavlink packets to report the values of video RSSI and FEC etc and pixelpilot uses those values in OSD.

The way pixelpilot distinguishes wfb-ng mavlink message from other mavlink radio status packets is by hardcoded `system_id` and `component_id` parameters of the packet:
https://github.com/OpenIPC/PixelPilot_rk/blob/e070b646af6b948c462f5287a58d03fe98f89989/src/mavlink.c#L276-L277

However those values can be tweaked in wfb-ng config file: https://github.com/svpcom/wfb-ng/blob/f08a07304903cb0b57c7ae25c7e71cc7aeab2811/wfb_ng/conf/master.cfg#L226-L228

So I think we should provide some knobs to select different values of those parameters.

However it might be not needed if we implement #18 and get the same (or even more detailed) information from wfb binary log

**Comment by luastoned** [comment]
Like I posted in the other issue, I think OSD elements should be more decoupled from PP itself, maybe we can have a chat in the group?

**Comment by zhouruixi** [comment]
I don't know if there is a concept of layers in drm. Can we separate the OSD display program and display OSD on the upper layer of the video, and finally merge the image and display it on the monitor? If plan to make a control menu similar to rubyfpv later, we can put control menu into the OSD display program.

**Comment by seriyps** [comment]
There are layers (called "planes") in DRM and pixelpilot indeed draws the video and OSD on separate planes. However I doubt OSD can be easily rendered to pixelpilot's plane by separate program... but I'm not an expert.

**Comment by seriyps** [comment]
@zhouruixi @luastoned I created a separate ticket #27 to discuss how can we improve OSD

**Comment by seriyps** [comment]
@zhouruixi this is the man page that describes the Linux subsystem that is used by Pixelpilot for displaying the video: https://manpages.org/drm-kms/7

It is very low-level which I believe allows it to have the lowest possible latency, but at the same time it can not share the monitor with other window - pixelpilot works on the same level where it is usually X server or Wayland

**Comment by seriyps** [comment]
Fixed by #36
